// ============================================================
// frootze — 5 Shareable Tree Templates
// Used in the Share modal radial tree renderer
// ============================================================

export const TEMPLATES = [
  {
    id: 'classic',
    name: 'Classic Tree',
    nameTa: 'பாரம்பரிய மரம்',
    emoji: '🌳',
    bg: '#F0FDF4',
    bgGradient: ['#064E3B', '#065F46'],
    trunk: '#92400E',
    branch: '#15803D',
    nodeFill: '#DCFCE7',
    nodeStroke: '#16A34A',
    nodeText: '#14532D',
    youFill: '#15803D',
    youText: '#FFFFFF',
    labelColor: '#166534',
    titleColor: '#FFFFFF',
    footerBg: '#064E3B',
    footerText: '#A7F3D0',
  },
  {
    id: 'royal',
    name: 'Royal Gold',
    nameTa: 'அரச தங்கம்',
    emoji: '👑',
    bg: '#1E1B4B',
    bgGradient: ['#1E1B4B', '#312E81'],
    trunk: '#D97706',
    branch: '#B45309',
    nodeFill: '#FEF3C7',
    nodeStroke: '#D97706',
    nodeText: '#78350F',
    youFill: '#D97706',
    youText: '#FFFFFF',
    labelColor: '#FDE68A',
    titleColor: '#FDE68A',
    footerBg: '#1E1B4B',
    footerText: '#FDE68A',
  },
  {
    id: 'heritage',
    name: 'Tamil Heritage',
    nameTa: 'தமிழ் பாரம்பரியம்',
    emoji: '🏺',
    bg: '#FEF3C7',
    bgGradient: ['#7C2D12', '#9A3412'],
    trunk: '#7C2D12',
    branch: '#B45309',
    nodeFill: '#FFF7ED',
    nodeStroke: '#C2410C',
    nodeText: '#7C2D12',
    youFill: '#C2410C',
    youText: '#FFFFFF',
    labelColor: '#FED7AA',
    titleColor: '#FFFFFF',
    footerBg: '#7C2D12',
    footerText: '#FED7AA',
  },
  {
    id: 'minimal',
    name: 'Modern Minimal',
    nameTa: 'நவீன மினிமல்',
    emoji: '✨',
    bg: '#FFFFFF',
    bgGradient: ['#F8FAFC', '#F1F5F9'],
    trunk: '#6366F1',
    branch: '#818CF8',
    nodeFill: '#EEF2FF',
    nodeStroke: '#6366F1',
    nodeText: '#312E81',
    youFill: '#6366F1',
    youText: '#FFFFFF',
    labelColor: '#6366F1',
    titleColor: '#312E81',
    footerBg: '#EEF2FF',
    footerText: '#6366F1',
  },
  {
    id: 'night',
    name: 'Night Sky',
    nameTa: 'இரவு வானம்',
    emoji: '🌙',
    bg: '#0F172A',
    bgGradient: ['#0F172A', '#1E293B'],
    trunk: '#7C3AED',
    branch: '#A78BFA',
    nodeFill: '#1E1B4B',
    nodeStroke: '#7C3AED',
    nodeText: '#C4B5FD',
    youFill: '#7C3AED',
    youText: '#FFFFFF',
    labelColor: '#A78BFA',
    titleColor: '#E2E8F0',
    footerBg: '#0F172A',
    footerText: '#A78BFA',
  },
];
